<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Is Gold</name>
  <uuid>b742978c-ca37-452f-8712-4ddeb1564da6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the loyalty of Customer is Gold 
then
	set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
