<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Is Platinum</name>
  <uuid>51bbde2f-e9f5-411b-b541-3e3dddf50b11</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the loyalty of Customer is Platinum 
then
	set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
